# frozen_string_literal: true

ADDRESSES = [{ name: 'Mad', surname: 'Max',
               address: 'Tomsk, ul. Pobedy, d. 155 ',
               phone: '+7(904)2112313' },
             { name: 'Lev', surname: 'Leshenko',
               address: 'Vorkuta, ul. Oplesnina, d. 46',
               phone: '+7(321)1315437' },
             { name: 'Gosha', surname: 'Kucenko',
               address: 'Kazan, ul. Dimitrova, d. 72',
               phone: '+7(321)1226123' },
             { name: 'No', surname: 'Body',
              address: 'Samara, ul. Dimitrova, d. 152 ',
              phone: '+7(904)2112315' },
             { name: 'Name', surname: 'Less',
               address: 'Saratov, ul. Babyshkina, d. 40',
               phone: '+7(321)1315430' },
             { name: 'Filipp', surname: 'Kirkorov',
               address: 'Moscow, ul. Dimitrova, d. 72',
               phone: '+7(321)1226124' },
             { name: 'Pac', surname: 'Man',
               address: 'Syktyvkar, ul. Garajnaya, d. 3 ',
               phone: '+7(904)2112313' },
             { name: 'Stas', surname: 'Mikhailov',
               address: 'Vyborg, ul. Oplesnina, d. 4',
               phone: '+7(321)1315437' },
             { name: 'Leonid', surname: 'Agutin',
               address: 'Vladimir, ul. Dimitrova, d. 72',
               phone: '+7(321)1226123' },
             { name: 'Nikolay', surname: 'Baskov',
                address: 'Omsk, ul. Porazheniya, d. 176 ',
                phone: '+7(904)2112312' },
             { name: 'Dima', surname: 'Bilan',
                address: 'Pechora, ul. Kirova, d. 46',
                phone: '+7(321)1315409' },
             { name: 'Alesha', surname: 'Popovich',
                address: 'Tyumen, ul. Cvetochnaya, d. 7',
                phone: '+7(321)1226151' }].freeze

Address.create(ADDRESSES)
